import {
  css3,
  docker,
  // cypress,
  figma,
  firebase,
  github,
  githubActions,
  gitlab,
  golang,
  javascript,
  jest,
  materialui,
  nextjs,
  nodejs,
  react,
  reactNative,
  redux,
  storybook,
  styledComponents,
  typescript,
} from "./technologies";

export default {
  title: "Where I have worked",
  companies: [
    {
      name: "Lisbon Nearshore",
      url: "https://lisbonnearshore.com/",
      role: "Senior Frontend Engineer",
      period: "Aug 2023 - Present",
      technologies: [
        react,
        javascript,
        typescript,
        storybook,
        figma,
        materialui,
        jest,
        docker,
      ],
      responsabilities: [
        "Contribute to the ongoing development of Fignum's client payment platform, focusing on a user-friendly interface for efficient transactions.",
        "Build and maintain a customized IT operations platform, simplifying client management and enhancing operational efficiency.",
        "Continuously revitalize the UI codebase, implementing best practices to improve maintainability and enhance the visual appeal of the platform.",
      ],
    },
    {
      name: "xgeeks",
      url: "https://xgeeks.io",
      role: "Senior Javascript Engineer",
      period: "Aug 2021 - Aug 2023",
      technologies: [
        react,
        nextjs,
        javascript,
        typescript,
        storybook,
        figma,
        styledComponents,
        jest,
        // cypress,
        github,
        githubActions,
      ],
      responsabilities: [
        "Work with project managers and other engineers to understand project requirements and deliver high-quality solutions.",
        "Write clean, maintainable, and scalable code that meets client needs and project deadlines.",
        "Communicate effectively with clients to understand their needs and provide technical solutions.",
      ],
    },
    {
      name: "Cazoo",
      url: "https://www.cazoo.co.uk",
      role: "Javascript Engineer",
      period: "Aug 2021 - Dec 2022",
      technologies: [
        react,
        nextjs,
        javascript,
        typescript,
        storybook,
        figma,
        styledComponents,
        jest,
        // cypress,
        github,
        githubActions,
      ],
      responsabilities: [
        "Develop and maintain the company's component libraries, ensuring accessibility, testing and cross-browser compatibility.",
        "Document design system components, usage, and best practices for internal stakeholders.",
        "Collaborate with designers, product managers, and engineers to ensure consistency and quality across all products.",
      ],
    },
    {
      name: "Glartek",
      url: "https://glartek.com",
      role: "FullStack Developer",
      period: "Feb 2021 - Aug 2021",
      technologies: [
        react,
        javascript,
        typescript,
        redux,
        golang,
        figma,
        materialui,
        jest,
        gitlab,
      ],
      responsabilities: [
        "Implement front-end features, including component-based UI design, routing, state management, and API integration.",
        "Ensure that developed applications are optimized for augmented reality and remote assistance use cases.",
        "Debug and troubleshoot code, and resolve technical issues in a timely manner.",
      ],
    },
    {
      name: "Freelancing",
      url: "https://www.linkedin.com/in/milton-boos-junior/",
      role: "FullStack Developer",
      period: "Jan 2020 - Jan 2021",
      technologies: [
        react,
        reactNative,
        javascript,
        typescript,
        redux,
        nodejs,
        firebase,
        figma,
        css3,
        styledComponents,
        jest,
        github,
        githubActions,
      ],
      responsabilities: [
        "Ensure that the developed platform meets the client's needs, including features such as task management, document sharing, and internal communication.",
        "Implement responsive marketing focused pages with animations.",
        "Provide dedicated maintanance for each of the products.",
      ],
    },
  ],
};
